import { Dimensions, Platform, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#F7F8FA',
  },
  flex: {
    flex: 1,
  },
  glass: {
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.72)',
    backgroundColor: 'rgba(255,255,255,0.58)',
    shadowColor: '#191F28',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 7,
  },
  mapScreen: {
    flex: 1,
    backgroundColor: '#D9EFF7',
  },
  mapCanvas: {
    flex: 1,
    backgroundColor: '#D8F0F8',
  },
  googleMapLayer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#E9EEF3',
  },
  mapFallback: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#E9EEF3',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 34,
  },
  mapFallbackTitle: {
    color: '#191F28',
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 10,
  },
  mapFallbackText: {
    color: '#6B7684',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
    textAlign: 'center',
  },
  land: {
    position: 'absolute',
    backgroundColor: '#EAF6D4',
    borderColor: '#B9E59C',
    borderWidth: 2,
  },
  landA: {
    width: width * 0.72,
    height: width * 0.78,
    left: -width * 0.1,
    top: 116,
    borderRadius: width * 0.24,
    transform: [{ rotate: '-16deg' }],
  },
  landB: {
    width: width * 0.78,
    height: width * 0.64,
    right: -width * 0.25,
    top: 64,
    borderRadius: width * 0.22,
    transform: [{ rotate: '12deg' }],
  },
  road: {
    position: 'absolute',
    height: 15,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderColor: '#C8D1DC',
    borderWidth: 2,
  },
  roadA: {
    width: width * 1.18,
    top: 234,
    left: -34,
    transform: [{ rotate: '-23deg' }],
  },
  roadB: {
    width: width * 1.05,
    top: 360,
    right: -70,
    transform: [{ rotate: '32deg' }],
  },
  roadC: {
    width: width * 0.9,
    top: 162,
    left: 22,
    transform: [{ rotate: '8deg' }],
  },
  river: {
    position: 'absolute',
    width: width * 0.42,
    height: '120%',
    right: -38,
    top: -70,
    backgroundColor: '#9AD9F8',
    transform: [{ rotate: '-14deg' }],
    borderLeftWidth: 8,
    borderLeftColor: 'rgba(255,255,255,0.6)',
  },
  pin: {
    position: 'absolute',
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#FFFFFF',
    shadowColor: '#191F28',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 14,
    elevation: 8,
  },
  searchBox: {
    position: 'absolute',
    top: Platform.OS === 'android' ? 26 : 8,
    left: 18,
    right: 18,
  },
  searchGlass: {
    height: 54,
    borderRadius: 22,
    paddingHorizontal: 17,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  searchInput: {
    flex: 1,
    height: 52,
    color: '#191F28',
    fontSize: 16,
    fontWeight: '700',
  },
  categoryRail: {
    position: 'absolute',
    top: Platform.OS === 'android' ? 90 : 72,
    left: 0,
    right: 0,
  },
  categoryRailContent: {
    paddingHorizontal: 18,
    gap: 8,
  },
  categoryChip: {
    height: 38,
    paddingHorizontal: 14,
    borderRadius: 19,
    backgroundColor: 'rgba(255,255,255,0.76)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.75)',
  },
  categoryChipOn: {
    backgroundColor: '#3182F6',
    borderColor: '#3182F6',
  },
  categoryChipText: {
    color: '#4E5968',
    fontSize: 13,
    fontWeight: '800',
  },
  categoryChipTextOn: {
    color: '#FFFFFF',
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 238,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#3182F6',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#3182F6',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.35,
    shadowRadius: 20,
    elevation: 9,
  },
  mapStatusBadge: {
    position: 'absolute',
    top: Platform.OS === 'android' ? 138 : 120,
    left: 18,
    right: 18,
    minHeight: 42,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  mapStatusText: {
    flex: 1,
    color: '#4E5968',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
  },
  mapControlStack: {
    position: 'absolute',
    right: 20,
    top: Platform.OS === 'android' ? 148 : 130,
    gap: 10,
  },
  mapRoundButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailSheet: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 92,
    borderRadius: 28,
    padding: 18,
  },
  detailTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  detailIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailTitle: {
    color: '#191F28',
    fontSize: 20,
    fontWeight: '900',
  },
  detailMeta: {
    marginTop: 3,
    color: '#6B7684',
    fontSize: 13,
    fontWeight: '700',
  },
  detailDesc: {
    color: '#4E5968',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '600',
  },
  infoGrid: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  infoBox: {
    flex: 1,
    minHeight: 74,
    padding: 13,
    borderRadius: 18,
    backgroundColor: 'rgba(242,244,246,0.72)',
  },
  infoLabel: {
    color: '#8B95A1',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 6,
  },
  infoText: {
    color: '#191F28',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
  },
  page: {
    paddingTop: Platform.OS === 'android' ? 30 : 12,
    paddingHorizontal: 18,
    paddingBottom: 112,
    backgroundColor: '#F7F8FA',
    gap: 14,
  },
  pageTitle: {
    color: '#191F28',
    fontSize: 28,
    fontWeight: '900',
    marginBottom: 2,
  },
  card: {
    borderRadius: 26,
    padding: 18,
    gap: 14,
  },
  badge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 32,
    paddingHorizontal: 12,
    borderRadius: 16,
    backgroundColor: '#EEF6FF',
  },
  badgeText: {
    color: '#3182F6',
    fontSize: 13,
    fontWeight: '900',
  },
  cardTitle: {
    color: '#191F28',
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '900',
  },
  textArea: {
    minHeight: 118,
    borderRadius: 20,
    padding: 16,
    textAlignVertical: 'top',
    backgroundColor: '#F2F4F6',
    color: '#191F28',
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '700',
  },
  captureDrop: {
    minHeight: 142,
    borderRadius: 24,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: '#B9D7FF',
    backgroundColor: '#EEF6FF',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
    gap: 6,
  },
  captureDropTitle: {
    color: '#191F28',
    fontSize: 17,
    fontWeight: '900',
  },
  captureDropSub: {
    color: '#6B7684',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
    textAlign: 'center',
  },
  capturePreview: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    padding: 12,
    borderRadius: 20,
    backgroundColor: '#F2F4F6',
  },
  captureImage: {
    width: 74,
    height: 74,
    borderRadius: 16,
    backgroundColor: '#E5E8EB',
  },
  capturePreviewInfo: {
    flex: 1,
    gap: 4,
  },
  extractingBox: {
    minHeight: 54,
    borderRadius: 18,
    paddingHorizontal: 14,
    backgroundColor: '#F2F8FF',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  extractingText: {
    flex: 1,
    color: '#3182F6',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '900',
  },
  fieldLabel: {
    color: '#8B95A1',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: -8,
  },
  fieldInput: {
    minHeight: 46,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#F2F4F6',
    color: '#191F28',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  fieldArea: {
    minHeight: 82,
    textAlignVertical: 'top',
  },
  demoRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  demoChip: {
    height: 36,
    paddingHorizontal: 13,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E5E8EB',
  },
  demoChipText: {
    color: '#4E5968',
    fontSize: 13,
    fontWeight: '800',
  },
  primaryButton: {
    minHeight: 52,
    borderRadius: 18,
    backgroundColor: '#3182F6',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  resultConfidence: {
    color: '#3182F6',
    fontSize: 13,
    fontWeight: '900',
  },
  resultTitle: {
    color: '#191F28',
    fontSize: 24,
    fontWeight: '900',
  },
  resultMeta: {
    color: '#6B7684',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  routeItem: {
    minHeight: 74,
    borderRadius: 24,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  routeIndex: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#3182F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  routeIndexText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  routeTitle: {
    color: '#191F28',
    fontSize: 17,
    fontWeight: '900',
  },
  routeMeta: {
    marginTop: 4,
    color: '#6B7684',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
  },
  legBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginLeft: 32,
    minHeight: 42,
  },
  legText: {
    color: '#3182F6',
    fontSize: 13,
    fontWeight: '900',
  },
  timelineItem: {
    minHeight: 78,
    borderRadius: 24,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  timelineTime: {
    width: 58,
    color: '#3182F6',
    fontSize: 17,
    fontWeight: '900',
  },
  settingRow: {
    minHeight: 78,
    borderRadius: 22,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
  },
  settingTitle: {
    color: '#191F28',
    fontSize: 16,
    fontWeight: '900',
  },
  settingDesc: {
    marginTop: 4,
    color: '#6B7684',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
  },
  tabBar: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: Platform.OS === 'android' ? 14 : 22,
    height: 70,
    borderRadius: 28,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tab: {
    flex: 1,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  tabText: {
    color: '#8B95A1',
    fontSize: 11,
    fontWeight: '900',
  },
  tabTextOn: {
    color: '#3182F6',
  },
  toast: {
    position: 'absolute',
    left: 32,
    right: 32,
    bottom: Platform.OS === 'android' ? 96 : 108,
    minHeight: 48,
    borderRadius: 24,
    backgroundColor: '#191F28',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  toastText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
});
