import { Dimensions, Platform, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#F7F8FA',
  },
  flex: {
    flex: 1,
  },
  glass: {
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.72)',
    backgroundColor: 'rgba(255,255,255,0.58)',
    shadowColor: '#191F28',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 7,
  },
  mapScreen: {
    flex: 1,
    backgroundColor: '#D9EFF7',
  },
  mapCanvas: {
    flex: 1,
    backgroundColor: '#D8F0F8',
  },
  googleMapLayer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#E9EEF3',
  },
  mapFallback: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#E9EEF3',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 34,
  },
  mapFallbackTitle: {
    color: '#191F28',
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 10,
  },
  mapFallbackText: {
    color: '#6B7684',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
    textAlign: 'center',
  },
  land: {
    position: 'absolute',
    backgroundColor: '#EAF6D4',
    borderColor: '#B9E59C',
    borderWidth: 2,
  },
  landA: {
    width: width * 0.72,
    height: width * 0.78,
    left: -width * 0.1,
    top: 116,
    borderRadius: width * 0.24,
    transform: [{ rotate: '-16deg' }],
  },
  landB: {
    width: width * 0.78,
    height: width * 0.64,
    right: -width * 0.25,
    top: 64,
    borderRadius: width * 0.22,
    transform: [{ rotate: '12deg' }],
  },
  road: {
    position: 'absolute',
    height: 15,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderColor: '#C8D1DC',
    borderWidth: 2,
  },
  roadA: {
    width: width * 1.18,
    top: 234,
    left: -34,
    transform: [{ rotate: '-23deg' }],
  },
  roadB: {
    width: width * 1.05,
    top: 360,
    right: -70,
    transform: [{ rotate: '32deg' }],
  },
  roadC: {
    width: width * 0.9,
    top: 162,
    left: 22,
    transform: [{ rotate: '8deg' }],
  },
  river: {
    position: 'absolute',
    width: width * 0.42,
    height: '120%',
    right: -38,
    top: -70,
    backgroundColor: '#9AD9F8',
    transform: [{ rotate: '-14deg' }],
    borderLeftWidth: 8,
    borderLeftColor: 'rgba(255,255,255,0.6)',
  },
  pin: {
    position: 'absolute',
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#FFFFFF',
    shadowColor: '#191F28',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 14,
    elevation: 8,
  },
  searchBox: {
    position: 'absolute',
    top: Platform.OS === 'android' ? 26 : 8,
    left: 18,
    right: 18,
  },
  searchGlass: {
    height: 54,
    borderRadius: 22,
    paddingHorizontal: 17,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  searchInput: {
    flex: 1,
    height: 52,
    color: '#191F28',
    fontSize: 16,
    fontWeight: '700',
  },
  categoryRail: {
    position: 'absolute',
    top: Platform.OS === 'android' ? 90 : 72,
    left: 0,
    right: 0,
  },
  categoryRailContent: {
    paddingHorizontal: 18,
    gap: 8,
  },
  categoryChip: {
    height: 38,
    paddingHorizontal: 14,
    borderRadius: 19,
    backgroundColor: 'rgba(255,255,255,0.76)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.75)',
  },
  categoryChipOn: {
    backgroundColor: '#3182F6',
    borderColor: '#3182F6',
  },
  categoryChipText: {
    color: '#4E5968',
    fontSize: 13,
    fontWeight: '800',
  },
  categoryChipTextOn: {
    color: '#FFFFFF',
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 238,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#3182F6',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#3182F6',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.35,
    shadowRadius: 20,
    elevation: 9,
  },
  routeSelectOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 40,
    elevation: 40,
  },
  routeGestureLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
  },
  routeFog: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(242, 244, 246, 0.56)',
  },
  routeEdgeTop: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 2,
    backgroundColor: '#050505',
  },
  routeEdgeBottom: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 2,
    backgroundColor: '#050505',
  },
  routeEdgeLeft: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: '#050505',
  },
  routeEdgeRight: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: '#050505',
  },
  routeSelectGuide: {
    position: 'absolute',
    zIndex: 5,
    top: Platform.OS === 'android' ? 92 : 84,
    left: 18,
    right: 18,
    minHeight: 58,
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  routeGuideIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
  },
  routeGuideTitle: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '900',
  },
  routeGuideSub: {
    color: '#4E5968',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 2,
  },
  routeResultSheet: {
    position: 'absolute',
    zIndex: 5,
    left: 14,
    right: 14,
    bottom: Platform.OS === 'android' ? 46 : 54,
    minHeight: 64,
    borderRadius: 26,
    paddingHorizontal: 18,
    paddingVertical: 13,
  },
  routeResultTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  routeResultTitle: {
    color: '#111827',
    fontSize: 22,
    fontWeight: '900',
  },
  routeSearchPanel: {
    position: 'absolute',
    zIndex: 6,
    top: Platform.OS === 'android' ? 162 : 154,
    left: 18,
    right: 18,
    maxHeight: 330,
    borderRadius: 24,
    padding: 14,
  },
  routeSearchInputRow: {
    minHeight: 48,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 13,
  },
  routeSearchInput: {
    flex: 1,
    color: '#191F28',
    fontSize: 15,
    fontWeight: '800',
  },
  routeSearchList: {
    marginTop: 10,
  },
  routeSearchRow: {
    minHeight: 58,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.72)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  routeEmptyText: {
    color: '#6B7684',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '800',
    padding: 10,
  },
  routeDoneButton: {
    minWidth: 58,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#3182F6',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  routeDoneText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  routeScheduleButton: {
    minHeight: 46,
    borderRadius: 20,
    backgroundColor: '#111827',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 12,
  },
  routeScheduleButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  routeSchedulePage: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 60,
    elevation: 60,
    backgroundColor: '#F7F8FA',
  },
  routeScheduleSafe: {
    flex: 1,
  },
  routeScheduleHeader: {
    minHeight: 62,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E8EB',
    backgroundColor: '#FFFFFF',
  },
  routeScheduleTitle: {
    color: '#111827',
    fontSize: 17,
    fontWeight: '900',
  },
  routeScheduleSub: {
    color: '#6B7684',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 2,
  },
  routeScheduleContent: {
    padding: 18,
    paddingBottom: 120,
    gap: 14,
  },
  mapStatusBadge: {
    position: 'absolute',
    top: Platform.OS === 'android' ? 138 : 120,
    left: 18,
    right: 18,
    minHeight: 42,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  mapStatusText: {
    flex: 1,
    color: '#4E5968',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
  },
  mapControlStack: {
    position: 'absolute',
    right: 20,
    top: Platform.OS === 'android' ? 148 : 130,
    gap: 10,
  },
  mapRoundButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailMiniAnimated: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 92,
    zIndex: 45,
    elevation: 45,
  },
  detailSheet: {
    flex: 1,
    borderRadius: 28,
    paddingHorizontal: 18,
    paddingTop: 9,
    paddingBottom: 16,
  },
  detailDragHandle: {
    alignSelf: 'center',
    width: 42,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#D1D6DB',
    marginBottom: 12,
  },
  detailTopCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  detailFullPage: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 55,
    elevation: 55,
    backgroundColor: '#F7F8FA',
  },
  detailFullHeader: {
    minHeight: Platform.OS === 'android' ? 64 : 58,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E8EB',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  detailBackButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F2F4F6',
  },
  detailFullTitle: {
    color: '#111827',
    fontSize: 17,
    fontWeight: '900',
  },
  detailFullContent: {
    padding: 18,
    paddingBottom: 120,
  },
  detailTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  detailIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailTitle: {
    color: '#191F28',
    fontSize: 20,
    fontWeight: '900',
  },
  detailMeta: {
    marginTop: 3,
    color: '#6B7684',
    fontSize: 13,
    fontWeight: '700',
  },
  detailDesc: {
    color: '#4E5968',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '600',
  },
  infoGrid: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  infoBox: {
    flex: 1,
    minHeight: 74,
    padding: 13,
    borderRadius: 18,
    backgroundColor: 'rgba(242,244,246,0.72)',
  },
  infoLabel: {
    color: '#8B95A1',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 6,
  },
  infoText: {
    color: '#191F28',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
  },
  detailTabRow: {
    marginTop: 16,
    minHeight: 46,
    borderRadius: 18,
    backgroundColor: '#F2F4F6',
    padding: 4,
    flexDirection: 'row',
    gap: 4,
  },
  detailTabButton: {
    flex: 1,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  detailTabButtonOn: {
    backgroundColor: '#111827',
  },
  detailTabText: {
    color: '#4E5968',
    fontSize: 13,
    fontWeight: '900',
  },
  detailTabTextOn: {
    color: '#FFFFFF',
  },
  detailTabPanel: {
    marginTop: 14,
    gap: 12,
  },
  detailSectionTop: {
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  detailSectionTitle: {
    color: '#191F28',
    fontSize: 16,
    fontWeight: '900',
  },
  photoRail: {
    gap: 10,
    paddingRight: 18,
  },
  placePhoto: {
    width: 154,
    height: 116,
    borderRadius: 18,
    backgroundColor: '#E5E8EB',
  },
  googleReviewCard: {
    borderRadius: 18,
    backgroundColor: 'rgba(242,244,246,0.78)',
    padding: 13,
    gap: 8,
  },
  googleReviewTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  googleReviewAuthor: {
    color: '#191F28',
    fontSize: 14,
    fontWeight: '900',
  },
  googleReviewMeta: {
    color: '#8B95A1',
    fontSize: 12,
    fontWeight: '800',
  },
  googleReviewText: {
    color: '#4E5968',
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '700',
  },
  starRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  starButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewComposer: {
    borderRadius: 20,
    backgroundColor: '#F7F8FA',
    padding: 14,
    gap: 10,
  },
  reviewInput: {
    minHeight: 92,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    color: '#191F28',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    paddingHorizontal: 13,
    paddingVertical: 12,
    textAlignVertical: 'top',
  },
  reviewSaveButton: {
    minHeight: 48,
    borderRadius: 17,
    backgroundColor: '#3182F6',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  reviewSaveText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  userReviewCard: {
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    padding: 13,
    gap: 8,
    borderWidth: 1,
    borderColor: '#E5E8EB',
  },
  emptyInlineText: {
    color: '#8B95A1',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '800',
  },
  routeExploreButton: {
    minHeight: 50,
    borderRadius: 18,
    backgroundColor: '#3182F6',
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  routeExploreButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  detailSaveButton: {
    marginTop: 14,
  },
  routeModeRow: {
    marginTop: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  routeModeChip: {
    flexGrow: 1,
    minWidth: 100,
    minHeight: 54,
    borderRadius: 16,
    paddingHorizontal: 9,
    paddingVertical: 8,
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderWidth: 1,
    borderColor: 'rgba(229,57,53,0.22)',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  routeModeChipOn: {
    backgroundColor: '#E53935',
    borderColor: '#E53935',
  },
  routeModeChipOff: {
    backgroundColor: 'rgba(242,244,246,0.72)',
    borderColor: 'rgba(139,149,161,0.18)',
  },
  routeModeLabel: {
    color: '#4E5968',
    fontSize: 12,
    fontWeight: '900',
  },
  routeModeValue: {
    color: '#191F28',
    fontSize: 11,
    fontWeight: '900',
    textAlign: 'center',
  },
  routeModeLabelOn: {
    color: '#FFFFFF',
  },
  routeSummaryBox: {
    marginTop: 12,
    borderRadius: 18,
    backgroundColor: '#FFF0F0',
    padding: 12,
    gap: 5,
  },
  routeSummaryTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  routeSummaryTitle: {
    color: '#191F28',
    fontSize: 16,
    fontWeight: '900',
    flex: 1,
  },
  routeSummarySub: {
    color: '#6B7684',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '800',
  },
  routeExploreMessage: {
    width: '100%',
    color: '#6B7684',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
  },
  transitRealtimeBox: {
    width: '100%',
    borderRadius: 16,
    backgroundColor: 'rgba(234,243,255,0.82)',
    padding: 12,
    gap: 5,
  },
  transitRealtimeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 2,
  },
  transitRealtimeTitle: {
    color: '#191F28',
    fontSize: 13,
    fontWeight: '900',
  },
  transitRealtimeText: {
    color: '#4E5968',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '800',
  },
  transitRealtimeMuted: {
    color: '#8B95A1',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '700',
  },
  page: {
    paddingTop: Platform.OS === 'android' ? 30 : 12,
    paddingHorizontal: 18,
    paddingBottom: 112,
    backgroundColor: '#F7F8FA',
    gap: 14,
  },
  settingsPage: {
    paddingTop: Platform.OS === 'android' ? 46 : 34,
  },
  pageTitle: {
    color: '#191F28',
    fontSize: 28,
    fontWeight: '900',
    marginBottom: 2,
  },
  card: {
    borderRadius: 26,
    padding: 18,
    gap: 14,
  },
  badge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 32,
    paddingHorizontal: 12,
    borderRadius: 16,
    backgroundColor: '#EEF6FF',
  },
  badgeText: {
    color: '#3182F6',
    fontSize: 13,
    fontWeight: '900',
  },
  cardTitle: {
    color: '#191F28',
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '900',
  },
  textArea: {
    minHeight: 118,
    borderRadius: 20,
    padding: 16,
    textAlignVertical: 'top',
    backgroundColor: '#F2F4F6',
    color: '#191F28',
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '700',
  },
  captureDrop: {
    minHeight: 142,
    borderRadius: 24,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: '#B9D7FF',
    backgroundColor: '#EEF6FF',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
    gap: 6,
  },
  captureDropTitle: {
    color: '#191F28',
    fontSize: 17,
    fontWeight: '900',
  },
  captureDropSub: {
    color: '#6B7684',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
    textAlign: 'center',
  },
  capturePreview: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    padding: 12,
    borderRadius: 20,
    backgroundColor: '#F2F4F6',
  },
  captureImage: {
    width: 74,
    height: 74,
    borderRadius: 16,
    backgroundColor: '#E5E8EB',
  },
  capturePreviewInfo: {
    flex: 1,
    gap: 4,
  },
  extractingBox: {
    minHeight: 54,
    borderRadius: 18,
    paddingHorizontal: 14,
    backgroundColor: '#F2F8FF',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  extractingText: {
    flex: 1,
    color: '#3182F6',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '900',
  },
  fieldLabel: {
    color: '#8B95A1',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: -8,
  },
  fieldInput: {
    minHeight: 46,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#F2F4F6',
    color: '#191F28',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  fieldArea: {
    minHeight: 82,
    textAlignVertical: 'top',
  },
  demoRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  demoChip: {
    height: 36,
    paddingHorizontal: 13,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E5E8EB',
  },
  demoChipText: {
    color: '#4E5968',
    fontSize: 13,
    fontWeight: '800',
  },
  primaryButton: {
    minHeight: 52,
    borderRadius: 18,
    backgroundColor: '#3182F6',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  secondaryButton: {
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: '#EAF3FF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  secondaryButtonText: {
    color: '#3182F6',
    fontSize: 14,
    fontWeight: '900',
  },
  resultConfidence: {
    color: '#3182F6',
    fontSize: 13,
    fontWeight: '900',
  },
  resultTitle: {
    color: '#191F28',
    fontSize: 24,
    fontWeight: '900',
  },
  resultMeta: {
    color: '#6B7684',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  routeItem: {
    minHeight: 74,
    borderRadius: 24,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  routeIndex: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#3182F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  routeIndexText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  routeTitle: {
    color: '#191F28',
    fontSize: 17,
    fontWeight: '900',
  },
  routeMeta: {
    marginTop: 4,
    color: '#6B7684',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
  },
  legBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginLeft: 32,
    minHeight: 42,
  },
  legText: {
    color: '#3182F6',
    fontSize: 13,
    fontWeight: '900',
  },
  collectionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 14,
  },
  collectionCountBadge: {
    minWidth: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  collectionCountText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  collectionActions: {
    flexDirection: 'row',
    gap: 8,
  },
  collectionActionButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: '#3182F6',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  collectionDeleteButton: {
    backgroundColor: '#FFF0F0',
  },
  collectionActionText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  collectionDeleteText: {
    color: '#FF3B30',
  },
  collectionTabs: {
    paddingRight: 18,
    gap: 8,
  },
  collectionTab: {
    minHeight: 42,
    borderRadius: 21,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 13,
    borderWidth: 1,
    borderColor: '#E5E8EB',
  },
  collectionTabOn: {
    backgroundColor: '#111827',
    borderColor: '#111827',
  },
  collectionDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
  },
  collectionIconChip: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  collectionTabText: {
    color: '#4E5968',
    fontSize: 13,
    fontWeight: '900',
  },
  collectionTabTextOn: {
    color: '#FFFFFF',
  },
  collectionTabCount: {
    color: '#8B95A1',
    fontSize: 12,
    fontWeight: '900',
  },
  collectionPlaceRow: {
    minHeight: 62,
    borderRadius: 18,
    backgroundColor: 'rgba(242,244,246,0.76)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    paddingHorizontal: 12,
  },
  collectionRouteRow: {
    minHeight: 76,
    borderRadius: 20,
    backgroundColor: 'rgba(234,243,255,0.86)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    paddingHorizontal: 12,
  },
  collectionRouteSteps: {
    marginTop: 4,
    color: '#3182F6',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '800',
  },
  collectionPlaceIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  collectionPickerOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 50,
    justifyContent: 'flex-end',
  },
  collectionPickerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(25, 31, 40, 0.22)',
  },
  collectionPickerSheet: {
    marginHorizontal: 14,
    marginBottom: Platform.OS === 'android' ? 96 : 108,
    borderRadius: 28,
    padding: 16,
    gap: 10,
  },
  collectionPickerTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 2,
  },
  collectionPickerTitle: {
    color: '#111827',
    fontSize: 20,
    fontWeight: '900',
  },
  collectionPickerSub: {
    color: '#6B7684',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 4,
  },
  collectionPickerRow: {
    minHeight: 58,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.76)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    paddingHorizontal: 12,
  },
  collectionCreatorOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 60,
    justifyContent: 'flex-end',
  },
  collectionCreatorSheet: {
    marginHorizontal: 14,
    marginBottom: Platform.OS === 'android' ? 96 : 108,
    borderRadius: 28,
    padding: 16,
    gap: 12,
  },
  collectionPreviewRow: {
    minHeight: 58,
    borderRadius: 18,
    backgroundColor: 'rgba(242,244,246,0.76)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 12,
  },
  collectionPreviewIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  collectionNameInput: {
    flex: 1,
    minHeight: 52,
    color: '#111827',
    fontSize: 17,
    fontWeight: '900',
    paddingVertical: 0,
  },
  collectionOptionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  collectionIconOption: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E5E8EB',
  },
  collectionIconOptionOn: {
    backgroundColor: '#111827',
    borderColor: '#111827',
  },
  collectionColorRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 9,
  },
  collectionColorOption: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.92)',
  },
  collectionColorOptionOn: {
    borderColor: '#111827',
  },
  collectionCreatorActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 2,
  },
  collectionSaveButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: '#3182F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  collectionSaveText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  aiLoadingCard: {
    borderRadius: 26,
    padding: 22,
    alignItems: 'center',
    gap: 10,
  },
  aiLoadingTitle: {
    color: '#191F28',
    fontSize: 16,
    fontWeight: '900',
  },
  aiLoadingText: {
    color: '#FF7A00',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '800',
    textAlign: 'center',
  },
  aiRegionRow: {
    paddingRight: 18,
    gap: 8,
    marginBottom: 14,
  },
  aiRegionChip: {
    minHeight: 42,
    borderRadius: 21,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E8EB',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 13,
  },
  aiRegionChipOn: {
    backgroundColor: '#111827',
    borderColor: '#111827',
  },
  aiRegionText: {
    color: '#4E5968',
    fontSize: 13,
    fontWeight: '900',
  },
  aiRegionCount: {
    color: '#8B95A1',
    fontSize: 12,
    fontWeight: '900',
  },
  aiRegionTextOn: {
    color: '#FFFFFF',
  },
  aiDateRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  aiDateButton: {
    flex: 1,
    minHeight: 38,
    borderRadius: 14,
    backgroundColor: '#F2F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  aiDateButtonText: {
    color: '#4E5968',
    fontSize: 12,
    fontWeight: '900',
  },
  aiSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 8,
  },
  aiMiniActions: {
    flexDirection: 'row',
    gap: 8,
  },
  aiMiniActionText: {
    color: '#3182F6',
    fontSize: 11,
    fontWeight: '900',
  },
  aiMiniActionTextMuted: {
    color: '#8B95A1',
    fontSize: 11,
    fontWeight: '900',
  },
  aiEmptyBox: {
    minHeight: 92,
    borderRadius: 18,
    backgroundColor: '#FFF7E8',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 14,
  },
  aiPlaceRow: {
    minHeight: 62,
    borderRadius: 18,
    backgroundColor: 'rgba(242,244,246,0.76)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  aiPlaceRowOn: {
    backgroundColor: '#EAF3FF',
    borderColor: 'rgba(49,130,246,0.22)',
  },
  aiGenerateButton: {
    minHeight: 54,
    borderRadius: 20,
    backgroundColor: '#FF7A00',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#FF7A00',
    shadowOpacity: 0.18,
    shadowRadius: 14,
    elevation: 4,
  },
  aiGenerateButtonOff: {
    opacity: 0.48,
  },
  aiGenerateText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  aiResultTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  aiEditText: {
    color: '#6B7684',
    fontSize: 12,
    fontWeight: '900',
  },
  aiDoneBadge: {
    minHeight: 28,
    borderRadius: 14,
    backgroundColor: '#FFF7E8',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  aiDoneText: {
    color: '#FF7A00',
    fontSize: 11,
    fontWeight: '900',
  },
  aiScheduleHeader: {
    minHeight: 58,
    borderRadius: 18,
    backgroundColor: '#FFF7E8',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  aiTimelineBlock: {
    position: 'relative',
    paddingLeft: 28,
    marginTop: 14,
  },
  aiTimelineDot: {
    position: 'absolute',
    left: 0,
    top: 6,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
  },
  aiTimelineDotText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '900',
  },
  aiTimelineCard: {
    borderRadius: 20,
    backgroundColor: '#F7F8FA',
    padding: 13,
    gap: 8,
  },
  aiTimelineTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  aiDurationText: {
    color: '#6B7684',
    fontSize: 12,
    fontWeight: '900',
  },
  aiActivityBox: {
    minHeight: 36,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 10,
  },
  aiActivityText: {
    color: '#191F28',
    fontSize: 12,
    fontWeight: '900',
    flex: 1,
  },
  aiTipBox: {
    borderRadius: 14,
    backgroundColor: '#FFF7E8',
    padding: 10,
  },
  aiTipText: {
    color: '#8A4B00',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '800',
  },
  aiHoursText: {
    color: '#00A86B',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '900',
  },
  aiMoveBox: {
    alignSelf: 'flex-start',
    minHeight: 32,
    borderRadius: 16,
    backgroundColor: '#FFF0F0',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    marginTop: 8,
  },
  aiMoveText: {
    color: '#E53935',
    fontSize: 12,
    fontWeight: '900',
  },
  timelineItem: {
    minHeight: 78,
    borderRadius: 24,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  timelineTime: {
    width: 58,
    color: '#3182F6',
    fontSize: 17,
    fontWeight: '900',
  },
  settingRow: {
    minHeight: 78,
    borderRadius: 22,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
  },
  settingTitle: {
    color: '#191F28',
    fontSize: 16,
    fontWeight: '900',
  },
  settingDesc: {
    marginTop: 4,
    color: '#6B7684',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
  },
  authHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
  },
  authAvatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#EAF3FF',
  },
  authAvatarFallback: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#EAF3FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  authWorkspaceBox: {
    borderRadius: 18,
    backgroundColor: '#F7F8FA',
    padding: 13,
    gap: 4,
  },
  authLabel: {
    color: '#8B95A1',
    fontSize: 11,
    fontWeight: '900',
  },
  authWorkspaceText: {
    color: '#191F28',
    fontSize: 13,
    fontWeight: '900',
  },
  authModeRow: {
    minHeight: 48,
    borderRadius: 18,
    padding: 4,
    backgroundColor: '#F2F4F6',
    flexDirection: 'row',
    alignItems: 'center',
  },
  authModeButton: {
    flex: 1,
    height: 40,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  authModeButtonOn: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#191F28',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 2,
  },
  authModeText: {
    color: '#8B95A1',
    fontSize: 13,
    fontWeight: '900',
  },
  authModeTextOn: {
    color: '#3182F6',
  },
  authGenderRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  authGenderChip: {
    minHeight: 38,
    borderRadius: 19,
    backgroundColor: '#F2F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 13,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  authGenderChipOn: {
    backgroundColor: '#EAF3FF',
    borderColor: 'rgba(49,130,246,0.22)',
  },
  authGenderText: {
    color: '#6B7684',
    fontSize: 12,
    fontWeight: '900',
  },
  authGenderTextOn: {
    color: '#3182F6',
  },
  authButtonDisabled: {
    opacity: 0.58,
  },
  authMessage: {
    color: '#6B7684',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '800',
  },
  tabBar: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: Platform.OS === 'android' ? 14 : 22,
    height: 70,
    borderRadius: 28,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tab: {
    flex: 1,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  tabText: {
    color: '#8B95A1',
    fontSize: 11,
    fontWeight: '900',
  },
  tabTextOn: {
    color: '#3182F6',
  },
  toast: {
    position: 'absolute',
    left: 32,
    right: 32,
    bottom: Platform.OS === 'android' ? 96 : 108,
    minHeight: 48,
    borderRadius: 24,
    backgroundColor: '#191F28',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  toastText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
});
